# Project
mod_version=1.0.21
group=org.cyclops.integratedscripting
java_version=25

# Common
minecraft_version=26.1.1
mod_name=IntegratedScripting
mod_author=rubensworks (aka kroeser)
mod_id=integratedscripting
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedScripting
issue_tracker_url=https://github.com/CyclopsMC/IntegratedScripting/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-scripting
description=Create scripts for handling operations in Integrated Dynamics.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=889785
modrinth_project_id=uDJkuFRe

# NeoForge
neoforge_version=26.1.1.1-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-scripting.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
graal_version=25.0.1
cyclopscore_version=1.25.5-974
integrateddynamics_version=1.24.1-1707
commoncapabilities_version=2.9.7-335
