# Project
mod_version=1.0.28
group=org.cyclops.integratedscripting
java_version=25

# Common
minecraft_version=26.1.2
mod_name=IntegratedScripting
mod_author=rubensworks (aka kroeser)
mod_id=integratedscripting
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedScripting
issue_tracker_url=https://github.com/CyclopsMC/IntegratedScripting/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-scripting
description=Create scripts for handling operations in Integrated Dynamics.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=889785
modrinth_project_id=uDJkuFRe

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-scripting.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true

# Dependencies
graal_version=25.2.4
cyclopscore_version=1.30.1-1051
integrateddynamics_version=1.32.11-1809
commoncapabilities_version=2.11.4-344
