modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedScripting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-scripting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedscripting"
version="${file.jarVersion}"
displayName="IntegratedScripting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-scripting.json"
description='''
Create scripts for handling operations in Integrated Dynamics.
'''
[[dependencies.integratedscripting]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.19.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.8.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.21.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,]"
    ordering="NONE"
    side="BOTH"
