modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedScripting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-scripting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedscripting"
version="${file.jarVersion}"
displayName="IntegratedScripting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-scripting.json"
description='''
Create scripts for handling operations in Integrated Dynamics.
'''
[[dependencies.integratedscripting]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="commoncapabilities"
    type="required"
    versionRange="[2.9.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.21.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedscripting]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
